title: Ji Wang Kai's Homepage
page-top-title: Ji Wang Kai
top-section-bg-text: CControl Engineering
home-subtitle: Ji Wang Kai&ensp;|&ensp;季王锴
#copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
